#!/bin/bash
# Name: Frank Lewis
# NSID: fbl773
# Student #: 11194945
# Synopsis: "Beans on toast...weird."

echo \n************************ Begin ADWatch Tests ****************************
FAILEDTESTS=""
FAILEDCOUNT=0
cd ./CI
# Check for directory
if [[ -d ./ADWatch_CI_Tests ]]
then
	cd ./ADWatch_CI_Tests
else
	echo Directory ADWatch_CI_Tests not found. Abort.
	exit 1
fi
# Run all .out files
for t in *.out
do
	echo running $t...
	#Run and Check return
	./$t
	RET=$?
	if [ $RET -ne 0 ]; then
		echo "------------------- Test for $t FAILED --------------------------"
		let "FAILEDCOUNT++"
		FAILEDTESTS="$FAILEDTESTS$t "
	
	fi
done
echo "-------------------------------------------------------------------------"
echo "All tests run. $FAILEDCOUNT Failed Tests ( $FAILEDTESTS)"

exit 0

