#!/bin/bash
# Name: Frank Lewis
# NSID: fbl773
# Student #: 11194945
# Synopsis: "Beans on toast...weird."

echo \n************************ Begin ADWatch Tests ****************************

# Check for directory
if [[ -d ./ADWatch_CI_Tests ]]
then
	cd ./CI/ADWatch_CI_Tests
else
	echo Directory ADWatch_CI_Tests not found. Abort.
	exit 1
fi
pwd
# Run all .out files
for t in *.out
do
	echo running $t...
	#Run and Check return
	./$t
	RET=$?
	if [ $RET -ne 0 ]; then
		echo ******************* Test for $t FAILED **************************
	fi
done
exit 0

