

all: libadwfunc.a 
	@echo "************************ MADE LIBADWFUNC ***************************"


libadwfunc.a: 
	@echo "************** Making libadwfunc"
	libtool -static -o libadwfunc.a *.a
	@echo "************** libadwfunc made"

