name: ArduWatch-Ubuntu-Build

on:
  push:
    branches:
      - master
      - HiddenLeaf/*
      - Sakura-0-*
jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2 
    - name: make
      run: make
