name: ArduWatch-Mac-Build

on:
  push:
    branches:
      - master
      - HiddenLeaf/*
jobs:
  build:

    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v2 
    - name: configured
      run: ./CI/configure
    - name: make
      run: make
    - name: test
      run: ./CI/run_tests
    #- name: make check
    #  run: make check
    #- name: make distcheck
    #  run: make distcheck
