name: ArduWatch-Mac-Build

on:
  push:
    branches:
      - master
      - Dev/*
      - Sauske
jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2 
    #- name: configured
      #run: ./configure
    - name: make
      run: make
    #- name: make check
    #  run: make check
    #- name: make distcheck
    #  run: make distcheck
