name: ArduWatch-Ubuntu-Build

on:
  push:
    branches:
      - master
      - HiddenLeaf/*
jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2 
    - name: configured
      run: ./configure
    - name: make
      run: make
