name: C/C++ CI

on:
  push:
    branches: sauske-4-CI*

jobs:
  build:

    runs-on: macos-10.14
    
    steps:
    - uses: actions/checkout@sauske-4-CI
    #- name: configured
      #run: ./configure
    - name: make
      run: make
    #- name: make check
    #  run: make check
    #- name: make distcheck
    #  run: make distcheck
