name: ArduWatch-Mac-Build

on:
  push:
    branches:
    	- Sauske

jobs:
  build:

    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v2 
    #- name: configured
      #run: ./configure
    - name: make
      run: make
    #- name: make check
    #  run: make check
    #- name: make distcheck
    #  run: make distcheck
